import './globals.css'
import { Dancing_Script } from 'next/font/google'

const fonts = Dancing_Script({ subsets: ['latin'] })

export const metadata = {
  title: 'Hotels travel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.className}>{children}</body>
    </html>
  )
}
