import { CurrentPageProvider } from "@/store/CurrentProvider";
import Navbar from "../../components/atoms/button/navbar/navbar";
import "./globals.css";
import { Dancing_Script } from "next/font/google";
import ReservationProvider from "@/store/reservationsProvider";

const fonts = Dancing_Script({ subsets: ["latin"] });

export const metadata = {
  title: "Hotels travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReservationProvider>
        <CurrentPageProvider>
          <Navbar></Navbar>
          <body className={fonts.className}>{children}</body>
        </CurrentPageProvider>
      </ReservationProvider>
    </html>
  );
}
